version: '3.8'

services:
  api:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db

  db:
    image: 'postgres:latest'
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
